#!/bin/sh
# Runs the fresh verification scripts for the manuscript, regenerates the two
# generated LaTeX fragments (constants.tex, hashes.tex) and prints the SHA-256
# of the scripts.  Usage: sh verify/run_all.sh   (PYTHON=... to override)
set -eu
cd "$(dirname "$0")"
PY="${PYTHON:-python3}"
echo "== roots.py (exact rational root enclosures; writes ../constants.tex)"
"$PY" roots.py --tex ../constants.tex
echo "== counterexamples.py (exact rational witnesses)"
"$PY" counterexamples.py
echo "== identities.py (SymPy identities)"
"$PY" identities.py
echo "== violations.py (50-digit checks of the explicit constructions)"
"$PY" violations.py
echo "== SHA-256"
shasum -a 256 roots.py counterexamples.py identities.py violations.py
{
  printf '%s\n' '% Generated by verify/run_all.sh; do not edit by hand.'
  printf '%s\n' '\begin{tabular}{l l}' '\toprule' 'script & SHA-256 \\' '\midrule'
  shasum -a 256 roots.py counterexamples.py identities.py violations.py | awk '{printf "\\texttt{verify/%s} & \\texttt{%s} \\\\\n & \\texttt{%s} \\\\\n", $2, substr($1,1,32), substr($1,33,32)}'
  printf '%s\n' '\bottomrule' '\end{tabular}'
} > ../hashes.tex
echo "wrote ../hashes.tex"
