/**
 * topology.v1 assigns exact isomorphism classes to admitted network designs.
 * canonicalForm is a complete invariant for the lab's graphs: two graphs share a
 * form if and only if they are isomorphic. It is computed by deterministic
 * individualization-refinement (the nauty scheme without its extra invariants):
 * colour refinement (1-WL) to an equitable partition, then individualize each
 * vertex of the first non-singleton cell and recurse. Every discrete leaf gives
 * a relabeling; the form is the lexicographically smallest leaf encoding.
 * Automorphisms discovered at equal leaves prune sibling subtrees by orbit and
 * backjump to the divergence point, so rings, stars, complete and regular
 * graphs stay polynomial in practice. The search is still bounded: exceeding
 * SEARCH_BUDGET tree nodes throws rather than returning an unproven form.
 */
import { digestCanonical } from "@hraness/algal";
import { parseGraph, type Graph } from "./network";

/** Far above observed need (hundreds of nodes) for 24-node, 96-edge designs. */
const SEARCH_BUDGET = 200_000;

type Leaf = { path: number[]; labels: number[]; code: string };

type Search = {
  neighbors: number[][];
  adjacent: boolean[][];
  first: Leaf | null;
  best: Leaf | null;
  automorphisms: number[][];
  visited: number;
};

function compareSignatures(a: readonly number[], b: readonly number[]): number {
  for (let index = 0; index < a.length && index < b.length; index++) {
    if (a[index] !== b[index]) return a[index]! - b[index]!;
  }
  return a.length - b.length;
}

/** Rank vertices by signature; ranks depend only on signatures, never on IDs. */
function rank(signatures: readonly (readonly number[])[]): number[] {
  const order = signatures.map((_, vertex) => vertex).sort((a, b) => compareSignatures(signatures[a]!, signatures[b]!));
  const colours = Array<number>(signatures.length).fill(0);
  let colour = 0;
  for (let index = 1; index < order.length; index++) {
    if (compareSignatures(signatures[order[index - 1]!]!, signatures[order[index]!]!) !== 0) colour++;
    colours[order[index]!] = colour;
  }
  return colours;
}

function distinct(colours: readonly number[]): number {
  return new Set(colours).size;
}

/** 1-WL to the coarsest equitable refinement. Own colour leads, so cells only split. */
function refine(neighbors: readonly number[][], input: readonly number[]): number[] {
  let colours = [...input];
  let count = distinct(colours);
  for (;;) {
    const next = rank(colours.map((colour, vertex) => [colour, ...neighbors[vertex]!.map((other) => colours[other]!).sort((a, b) => a - b)]));
    const nextCount = distinct(next);
    if (nextCount === count) return next;
    colours = next;
    count = nextCount;
  }
}

/** Split `vertex` from its cell, ordering it just before the rest of that cell. */
function individualize(colours: readonly number[], vertex: number): number[] {
  const cell = colours[vertex]!;
  return rank(colours.map((colour, other) => [colour * 2 + Number(colour === cell && other !== vertex)]));
}

/** Members of the lowest-coloured non-singleton cell, or null when discrete. */
function targetCell(colours: readonly number[]): number[] | null {
  const sizes = new Map<number, number>();
  for (const colour of colours) sizes.set(colour, (sizes.get(colour) ?? 0) + 1);
  let target = Infinity;
  for (const [colour, size] of sizes) if (size > 1 && colour < target) target = colour;
  if (target === Infinity) return null;
  return colours.flatMap((colour, vertex) => colour === target ? [vertex] : []);
}

/** Upper-triangular adjacency bits of the graph relabeled by a discrete colouring. */
function encode(adjacent: readonly boolean[][], labels: readonly number[]): string {
  const vertexAt = Array<number>(labels.length);
  labels.forEach((label, vertex) => { vertexAt[label] = vertex; });
  let code = "";
  for (let a = 0; a < labels.length; a++) {
    for (let b = a + 1; b < labels.length; b++) code += adjacent[vertexAt[a]!]![vertexAt[b]!] ? "1" : "0";
  }
  return code;
}

function find(parent: number[], vertex: number): number {
  while (parent[vertex] !== vertex) {
    parent[vertex] = parent[parent[vertex]!]!;
    vertex = parent[vertex]!;
  }
  return vertex;
}

/**
 * True when `vertex` shares an orbit with an explored sibling under the group
 * generated by known automorphisms that fix the individualized path pointwise.
 * Such a subtree is an automorphic image of one already searched.
 */
function redundant(search: Search, path: readonly number[], vertex: number, explored: readonly number[]): boolean {
  const parent = search.neighbors.map((_, index) => index);
  for (const automorphism of search.automorphisms) {
    if (path.some((fixed) => automorphism[fixed] !== fixed)) continue;
    automorphism.forEach((image, source) => {
      const a = find(parent, source);
      const b = find(parent, image);
      if (a !== b) parent[a] = b;
    });
  }
  const root = find(parent, vertex);
  return explored.some((other) => find(parent, other) === root);
}

function divergence(a: readonly number[], b: readonly number[]): number {
  let depth = 0;
  while (a[depth] === b[depth]) depth++;
  return depth;
}

/**
 * Record a leaf. On an encoding equal to the first or best leaf, store the
 * automorphism mapping that leaf to this one and return the depth at which the
 * two paths diverge: the rest of this subtree is an image of explored work.
 */
function leaf(search: Search, labels: number[], path: number[]): number {
  const code = encode(search.adjacent, labels);
  const current: Leaf = { path, labels, code };
  if (search.first === null || search.best === null) {
    search.first = current;
    search.best = current;
    return Infinity;
  }
  for (const known of [search.first, search.best]) {
    if (code !== known.code) continue;
    const vertexAt = Array<number>(labels.length);
    labels.forEach((label, vertex) => { vertexAt[label] = vertex; });
    search.automorphisms.push(known.labels.map((label) => vertexAt[label]!));
    return divergence(known.path, path);
  }
  if (code < search.best.code) search.best = current;
  return Infinity;
}

/** Depth-first search; returns a backjump depth, or Infinity to continue normally. */
function explore(search: Search, colours: number[], path: number[]): number {
  if (++search.visited > SEARCH_BUDGET) {
    throw new Error(`topology search exceeded ${SEARCH_BUDGET} tree nodes`);
  }
  const cell = targetCell(colours);
  if (cell === null) return leaf(search, colours, path);
  const explored: number[] = [];
  for (const vertex of cell) {
    if (explored.length > 0 && redundant(search, path, vertex, explored)) continue;
    explored.push(vertex);
    const jump = explore(search, refine(search.neighbors, individualize(colours, vertex)), [...path, vertex]);
    if (jump < path.length) return jump;
  }
  return Infinity;
}

/**
 * Canonical string `topology.v1:<nodes>:<a-b,...>` whose edge list is the graph
 * relabeled by the minimal leaf. Equal exactly for isomorphic graphs.
 */
export function canonicalForm(input: Graph): string {
  const graph = parseGraph(input);
  const neighbors = Array.from({ length: graph.nodes }, (): number[] => []);
  const adjacent = Array.from({ length: graph.nodes }, () => Array<boolean>(graph.nodes).fill(false));
  for (const [a, b] of graph.edges) {
    neighbors[a]!.push(b);
    neighbors[b]!.push(a);
    adjacent[a]![b] = true;
    adjacent[b]![a] = true;
  }
  const search: Search = { neighbors, adjacent, first: null, best: null, automorphisms: [], visited: 0 };
  explore(search, refine(neighbors, Array<number>(graph.nodes).fill(0)), []);
  const code = search.best!.code;
  const edges: string[] = [];
  let bit = 0;
  for (let a = 0; a < graph.nodes; a++) {
    for (let b = a + 1; b < graph.nodes; b++) if (code[bit++] === "1") edges.push(`${a}-${b}`);
  }
  return `topology.v1:${graph.nodes}:${edges.join(",")}`;
}

/** ALGAL digestCanonical (SHA-256 over canonical JSON) of the form as a JSON string. */
export function topologyDigest(graph: Graph): `sha256:${string}` {
  return digestCanonical(canonicalForm(graph));
}

export function isomorphic(a: Graph, b: Graph): boolean {
  return canonicalForm(a) === canonicalForm(b);
}

/** Input indices grouped by topology digest; classes sorted by digest, members ascending. */
export function topologyClasses(graphs: Graph[]): { digest: string; members: number[] }[] {
  const classes = new Map<string, number[]>();
  graphs.forEach((graph, index) => {
    const digest = topologyDigest(graph);
    const members = classes.get(digest);
    if (members === undefined) classes.set(digest, [index]);
    else members.push(index);
  });
  return [...classes].sort(([a], [b]) => a < b ? -1 : a > b ? 1 : 0).map(([digest, members]) => ({ digest, members }));
}
